using Microsoft.EntityFrameworkCore;

namespace JobSearch.Data;

// Checked before generating (skip the API call entirely if there's nothing to spend) and
// applied only after a successful result — never before/during generation, and never on
// failure, so there's no refund path to build.
public static class CreditService
{
    public static async Task<bool> HasCreditAsync(AppDbContext db, int userId)
    {
        var user = await db.Users.FindAsync(userId);
        return user is not null && user.CreditBalance > 0;
    }

    // Guarded by User.CreditVersion, an optimistic concurrency token — two concurrent requests
    // that both passed HasCreditAsync with 1 credit left can no longer both commit a decrement:
    // whichever SaveChangesAsync lands first bumps the version, and the second's save then
    // fails with DbUpdateConcurrencyException instead of silently overwriting it. Returns
    // whether it actually decremented, though callers don't block delivery on it — the content
    // was already generated by this point (see above), and withholding it now would just waste
    // the API call for nothing.
    public static async Task<bool> SpendCreditAsync(AppDbContext db, int userId)
    {
        var user = await db.Users.FindAsync(userId);
        if (user is null || user.CreditBalance <= 0) return false;

        user.CreditBalance -= 1;
        user.CreditVersion += 1;
        try
        {
            await db.SaveChangesAsync();
            return true;
        }
        catch (DbUpdateConcurrencyException)
        {
            return false;
        }
    }
}
